### PR TITLE
Update calico install in e2e test

### PR DESCRIPTION
**Pull request by psschwei**
Signed-off-by: Paul S. Schweigert <paul@paulschweigert.com>

### CODE REVIEW

**Comment by psschwei** [comment]
@jwcesign can you take a look at the failing cri-o tests?

**Comment by jwcesign** [comment]
sure

**Comment by jwcesign** [comment]
Hi, @psschwei , so it doesn't need to be fixed?

**Comment by psschwei** [comment]
Yeah, given #217 we can ignore these

**Pull request closed without merging**
