### PR TITLE
Fix default ksvc url

### PR DESCRIPTION
**Pull request by jwcesign**
Signed-off-by: jwcesign <jiangwei115@huawei.com>

# Changes

- :broom: Update or clean up current behavior

/kind cleanup

Fixes none

**Release Note**

```release-note
none
```

**Docs**

```docs
none
```

### CODE REVIEW

**Comment by jwcesign** [comment]
cc @psschwei

**Comment by jwcesign** [comment]
will find out reason

**Comment by psschwei** [comment]
From the logs:

`freeze_test.go:225: Check resume state error:request svc error:response code is:404, request url:http://127.0.0.1:31537/, requrst host:sleeptalker.default.svc.cluster.local`

Looks like this may be getting tripped up by the changes we made in https://github.com/knative/serving/pull/13259 ... wondering if [configuring DNS](https://knative.dev/docs/install/yaml-install/serving/install-serving-with-yaml/#configure-dns) would fix it?

**Comment by jwcesign** [comment]
> 31537

It did request with host, I think It will not help, but I will try it

**Comment by jwcesign** [comment]
I find the reason, the kingress resource only has cluster local:
```yaml
-> # kubectl get kingress -A -oyaml
apiVersion: v1
items:
- apiVersion: networking.internal.knative.dev/v1alpha1
  kind: Ingress
  metadata:
    annotations:
      networking.internal.knative.dev/rollout: '{"configurations":[{"configurationName":"sleeptalker","percent":100,"revisions":[{"revisionName":"sleeptalker-00001","percent":100}],"stepParams":{}}]}'
      networking.knative.dev/ingress.class: kourier.ingress.networking.knative.dev
      serving.knative.dev/creator: kubernetes-admin
      serving.knative.dev/lastModifier: kubernetes-admin
    creationTimestamp: "2022-10-26T13:46:04Z"
    finalizers:
    - ingresses.networking.internal.knative.dev
    generation: 1
    labels:
      serving.knative.dev/route: sleeptalker
      serving.knative.dev/routeNamespace: default
      serving.knative.dev/service: sleeptalker
    name: sleeptalker
    namespace: default
    ownerReferences:
    - apiVersion: serving.knative.dev/v1
      blockOwnerDeletion: true
      controller: true
      kind: Route
      name: sleeptalker
      uid: 15aef40b-542c-4a67-a506-204f243ccd54
    resourceVersion: "7999"
    uid: 500e6340-650c-4fe4-9e1b-6e368e951370
  spec:
    httpOption: Enabled
    rules:
    - hosts:
      - sleeptalker.default
      - sleeptalker.default.svc
      - sleeptalker.default.svc.cluster.local
      http:
        paths:
        - splits:
          - appendHeaders:
              Knative-Serving-Namespace: default
              Knative-Serving-Revision: sleeptalker-00001
            percent: 100
            serviceName: sleeptalker-00001
            serviceNamespace: default
            servicePort: 80
      visibility: ClusterLocal
  status:
    conditions:
```

**Comment by jwcesign** [comment]
no matter what next, but this is a reasonable fix.
cc @psschwei

**Review by psschwei — COMMENTED** [review]
:heart: 

/lgtm
/approve

**Pull request merged**
