### PR TITLE
Add e2e for container-freezer based on crio

### PR DESCRIPTION
**Pull request by jwcesign**
Signed-off-by: jiang wei <jwcesign@gmail.com>

# Changes

* Add e2e test for crio runtime

/kind enhancement
related https://github.com/knative-sandbox/container-freezer/issues/18

**Release Note**

```release-note
none
```

**Docs**

```docs
none
```

### CODE REVIEW

**Comment by jwcesign** [comment]
cc @psschwei

**Comment by jwcesign** [comment]
cc @psschwei

**Review by psschwei — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
