### PR TITLE
Adding basic template, OWNERS ids

### PR DESCRIPTION
**Pull request by psschwei**
/assign @julz @markusthoemmes

### CODE REVIEW

**Review by julz — APPROVED** [review]
/lgtm

**Comment by psschwei** [comment]
checking prow...
/retest

**Comment by psschwei** [comment]
The tests are failing here because the test infrastructure hasn't been set up yet :) But on the plus side, Prow _is_ setup.

Per the [setup instructions](https://github.com/knative/test-infra/blob/main/guides/prow_knative_setup.md#setting-up-prow-for-a-new-repo-reviewers-assignment-and-auto-merge), adding the OWNERS files (i.e. this PR) should be done before adding the presubmit-tests, etc files. 

Since the PR was approved by @julz (though for some reason the approved label wasn't added automatically), I don't see any reason why we shouldn't just merge this in.

(let me see if I can add the approved label)
/approve

**Comment by psschwei** [comment]
> Needs approval from an approver in each of these files:
>    OWNERS

So we need an owners file to merge this, but there won't be an owners file until this PR merges :laughing:

**Pull request merged**
